# Python-Numpy-Introduction

<img align="center" width="600" height="600"  src="images/numpyintro.png" > 

# Learning Agenda of this Notebook
1. **Getting Started**
    - `What is NumPy`
    - `Why use it?`
    - `Installation`
2. **Introduction to NumPy Array**
    - `Using NumPy`
    - `NumPy Arrays`
    - `Creating Numpy Arrays`
3. **Built-In Methods**
    - `arange`
    - `zeros and ones`
    - `linspace`
    - `eye`
4. **Random**
    - `ran`
    - `randn`
    - `randint`
5. **Array Attributes and Methods**
    - `reshape`
    - `shape`
    - `dtype`
6. **Numpy Indexing and Selection**
    - `Bracket Indexing and Selection`
    - `Broadcasting`
7. **Indexing 2D Array/Matrix**
    - `Fancy Indexing`
    - `Selection`
8. **Numpy Operations**
    - `Arithmetic`
    - `Universal Array Functions`
9. **Append, Concentrate and Stack**
    - `append`
    - `concatenate`
    - `stack` 

## What is NumPy?

- Numpy is a tool for mathematical computing and data preparation in Python. 
- It can be utilized to perform a number of mathematical operations on arrays such as trigonometric, statistical and algebraic routines. 
- This library provides many useful features including handling n-dimensional arrays, broadcasting, performing operations, data generation, etc., thus, it’s the fundamental package for scientific computing with Python. 
- It also provides a large collection of high-level mathematical functions to operate on arrays.

## Why use it?

It is incredibly fast, as it has bindings to C libraries. Python list has less properties than numpy array, which is why you will use arrays over lists. It helps in data preprocessing. Numpy is surprisingly compact, fast and easy to use, so let’s dive into installation.

#### Look other Python Libraries for Data Science
<img align="center" width="600" height="600"  src="images/top-10-python-libraries-for-data-science.jpg" > 

## Installation

The terminal on your machine is often used to install/manage/delete Python packages. Numpy too, can be installed from your command line using:

`pip3 install numpy` or `pip install numpy`

In [ ]:
import sys
sys.executable
# This command gives path of python installation 

## 2. Introduction to NumPy array
#### Using NumPy

Once the installation of the Numpy package is completed, the implementation in a Python file is done using the following command:

`import numpy as np`

Numpy has many different built-in functions and capabilities. In this lecture, we will focus on some of the most important aspects: vectors, arrays, matrices, number generation and few more. The rest of the Numpy capabilities can be explored in detail in the upcoming lectures.


#### NumPy Arrays

What are arrays? Arrays are a reserved space in memory for a list of values. These arrays essentially come in two flavors: vectors and matrices. Vectors are strictly one dimensional and matrices are two or more dimensional arrays. They certainly take part in the root architecture of programming and give a whole lot of new possibilities, which will be explored later on.


In [2]:
scalar = [1] #This is a scalar
vector = [2,3,4,4,5,43] # This is a vector
matrix = [[2,3,4,5],[5,42,1,1]] #This is a matrix

In [3]:
import numpy as np

In [ ]:
# print(dir(np))

In [4]:
print("Version of NumPy is : " ,np.__version__)
print("Path of NumPy is : " ,np.__path__)

Version of NumPy is :  1.26.4
Path of NumPy is :  ['/opt/anaconda3/lib/python3.11/site-packages/numpy']


#### Creating NumPy Arrays

The pre-built function `np.array` is the correct way to create an array. As you can see, first we import numpy as np, meaning that later we will access the numpy functions using the `np.functionName` format. Than we call the function `array` from it. The only required parameter for the array function is `data`, in a form of list. There are more parameters which also can be found in the numpy.array documentation. We either convert `data` into an array, or we specify the data inside the function.




In [5]:
np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [6]:
import numpy as np

data = [1,2,3]
arr = np.array(data)
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr = np.array([1,2,3])
print(type(arr))
# These two codes produce the same output when we print their type:

<class 'numpy.ndarray'>


In [8]:
arr, arr.dtype, arr.nbytes

(array([1, 2, 3]), dtype('int64'), 24)

In [9]:
a = np.array([2,3,4,5], dtype=np.uint8)

In [10]:
print("Array : ", a)
print("Type of a : ", type(a))
print("Dimensions of a : ", np.ndim(a))

Array :  [2 3 4 5]
Type of a :  <class 'numpy.ndarray'>
Dimensions of a :  1


In [11]:
a.dtype, a.nbytes

(dtype('uint8'), 4)

In [12]:
# empty numpy array
empty_arr = np.array([])
type(empty_arr)

numpy.ndarray

In [13]:
# numpy array from scalar
scalar_arr = np.array(5)
scalar_arr, type(scalar_arr), scalar_arr.ndim

(array(5), numpy.ndarray, 0)

#### Note:
- Both cases work perfectly fine. Other significant parameters to be considered are dtype, copy, ndmin, etc. Every array consists of two parts, the value and the index. The value is the actual numbers the array holds and the index is the position of the value in the array. This is essential, because it allows you to access certain values just by knowing their index, or finding the index of a certain value/s. We will go deeper in indexing later on in upcoming lectures.

In [14]:
print(dir(arr))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

## 3. Built-In Methods

Numpy allows us to use many built-in methods for generating arrays.
- `np.arange()` – array of arranged values from low to high value
- `np.zeros()` – array of zeros with specified shape
- `np.ones()` – similarly to zeros, array of ones with specified shape
- `np.linspace()` – array of linearly spaced numbers, with specified size
- `np.eye()` – two dimensional array with ones on the diagonal, zeros elsewhere

#### np.arange()

Numpy’s arange function will return evenly spaced values within a given interval. Works similarly to Python’s `range()` function. The only required parameter is ‘stop’, while all the other parameters are optional:

In [15]:
# Another useful parameter is `step` parameter, by default its value is 1. This value represents the numeric distance 
# b/w each integer generated by the function
print("Array : ",np.arange(start=5, stop=16))

Array :  [ 5  6  7  8  9 10 11 12 13 14 15]


In [16]:
# with the step of '2'
print("Array : ",np.arange(start=5, stop=16, step=2))

Array :  [ 5  7  9 11 13 15]


In [17]:
# Note that step size can be float
print("Array : ",np.arange(start=5, stop=16, step=1.75))

Array :  [ 5.    6.75  8.5  10.25 12.   13.75 15.5 ]


In [18]:
# We can also change the data-type of each element of the array
# By default , type is integer.
print("Array of Integers: ",np.arange(start=5, stop=16, step=2))
print("Array of Floats: ",np.arange(start=5, stop=16, step=2, dtype=float))

Array of Integers:  [ 5  7  9 11 13 15]
Array of Floats:  [ 5.  7.  9. 11. 13. 15.]


#### np.zeros() and np.ones()
Numpy provides functions that are able to create arrays of 1’s and 0’s. The required parameter for these functions is `shape`. By default, dtype of each element of array is `numpy.float64`. We can change dtype of elements of array by using parameter `dtype`.

In [19]:
# Create array filled with zero values
np.zeros(shape=4)

array([0., 0., 0., 0.])

In [20]:
# Create array filled with ones values
np.ones(shape=4)

array([1., 1., 1., 1.])

In [21]:
# Create array filled with ones values having int type
np.ones(shape=4, dtype=int)

array([1, 1, 1, 1])

In [22]:
# create multi-dimensional array with zeros
np.zeros(shape=(4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# create multi-dimensional array with ones
np.ones(shape=(6,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# create multi-dimensional array with ones having int data type
ones_arr = np.ones(shape= (5,6), dtype=np.uint8)
ones_arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=uint8)

In [27]:
ones_arr.ndim, ones_arr.dtype, ones_arr.nbytes

(2, dtype('uint8'), 30)

#### np.linspace()

Numpy’s linspace function will return evenly spaced numbers over a specified interval. Required parameters for this functions are `start` and `stop`. 

In [29]:
np.linspace(start=5, stop=1000)

array([   5.        ,   25.30612245,   45.6122449 ,   65.91836735,
         86.2244898 ,  106.53061224,  126.83673469,  147.14285714,
        167.44897959,  187.75510204,  208.06122449,  228.36734694,
        248.67346939,  268.97959184,  289.28571429,  309.59183673,
        329.89795918,  350.20408163,  370.51020408,  390.81632653,
        411.12244898,  431.42857143,  451.73469388,  472.04081633,
        492.34693878,  512.65306122,  532.95918367,  553.26530612,
        573.57142857,  593.87755102,  614.18367347,  634.48979592,
        654.79591837,  675.10204082,  695.40816327,  715.71428571,
        736.02040816,  756.32653061,  776.63265306,  796.93877551,
        817.24489796,  837.55102041,  857.85714286,  878.16326531,
        898.46938776,  918.7755102 ,  939.08163265,  959.3877551 ,
        979.69387755, 1000.        ])

**The parameter `num` specifies the number of samples to generate, and the default value is 50. The value defined in the parameter `num` must be non-negative. You are able to change the data type of your values using `dtype` as parameter.**

In [30]:
# we can change the data type of the each value by using dtype parameter
np.linspace(start=5, stop=15, num=9, dtype=int)

array([ 5,  6,  7,  8, 10, 11, 12, 13, 15])

In [ ]:
# np.array()
# np.arange(start, stop, step, dtype)
# np.zeros(shape) -> shape 1d, 2d, 3d, nd
# np.ones(shape) -> shape 1d,2d,3d, nd
# np.linspace(start, stop, num, dtype)

#### np.eye()

Numpy’s eye function will return Identity Matrix. The identity matrix is a square matrix that has 1’s along the main diagonal and 0’s for all other entries. This matrix is often written simply as `I`, and is special in that it acts like 1 in matrix multiplication. Required parameter for this function is `N`, number of rows in the output.

In [31]:
np.eye(N=6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

**This function can take a optional parameter `M`, which specifice the number of the columns. By default, its value is `N=M`**

In [ ]:
np.eye(N=5, M=6)

**This function can also take a very interesting optional parameter `k`. It is a integer and by default, its value is `0`. Index of the diagonal: 0 (the default) refers to the main diagonal. If a value of `k` is  positive, then it refers to an upper diagonal, and a negative valuerefers to a lower diagonal.**

In [32]:
# upper diagonal
np.eye(N=5, M=6 ,k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
# lower diagonal
np.eye(N=5, M=6, k=-1, dtype=np.int8)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]], dtype=int8)

In [ ]:
# np.array()
# np.arange(start, stop, step, dtype)
# np.zeros(shape) -> shape 1d, 2d, 3d, nd
# np.ones(shape) -> shape 1d,2d,3d, nd
# np.linspace(start, stop, num, dtype)
# np.eye(N=rows(int), M=columns(int), k=0(int), dtype=)

# 4. Random

Numpy allows you to use various functions to produce arrays with random values. To access these functions, first we have to access the `random` function itself. This is done using `np.random`, after which we specify which function we need. Here is a list of the most used random functions and their purpose:
- `np.random.rand()` – produce random values in the given shape from 0 to 1
- `np.random.randn()` – produce random values with a ‘standard normal’ distribution, from -1 to 1
- `np.random.randint()` – produce random numbers from low to high, specified as parameter

#### np.random.rand()
The rand function uses only one parameter which is the `shape` of the output. You need to specify the output format you need, whether it is one or two dimensional array. If there is no argument passed to the function, it returns a single value. Otherwise, it produces number of numbers as specified.

In [34]:
# This function gives a single value at a time if we don't pass value shape parameter
np.random.rand()

0.7885565743884096

In [35]:
# We can also generate randomly 2D array by giving values of rows and columns
np.random.rand(5,3)

array([[0.78552089, 0.49939613, 0.70427601],
       [0.50495044, 0.73796129, 0.62149634],
       [0.13771642, 0.55827253, 0.56110332],
       [0.50006283, 0.76209973, 0.78305355],
       [0.66056601, 0.37645242, 0.63088283]])

In [36]:
# We can also generate randomly 3D array
np.random.rand(3,4,5)

array([[[0.73129355, 0.26070913, 0.90284331, 0.91423245, 0.79039188],
        [0.0421461 , 0.52636379, 0.59642479, 0.05928162, 0.23962915],
        [0.5768528 , 0.86509024, 0.52663735, 0.0088608 , 0.69726831],
        [0.49714316, 0.82125633, 0.81857818, 0.61852459, 0.62106281]],

       [[0.83006477, 0.49512085, 0.11477262, 0.434635  , 0.36854712],
        [0.8050238 , 0.25374717, 0.78058699, 0.0198103 , 0.89934667],
        [0.16615247, 0.24554329, 0.22896414, 0.70181782, 0.2806712 ],
        [0.56906112, 0.53768885, 0.0304273 , 0.39434125, 0.99061527]],

       [[0.83529952, 0.72941211, 0.13090679, 0.00913375, 0.40214152],
        [0.90232145, 0.78710397, 0.92279694, 0.56481108, 0.30510369],
        [0.53538188, 0.56522753, 0.22647933, 0.21601636, 0.1794985 ],
        [0.58881856, 0.68071487, 0.09569676, 0.5268375 , 0.21406085]]])

#### np.random.randn()
The randn function is similar to the `rand` function, except it produces a number with standard normal distribution. What this means, is that it generates number with distribution of 1 and mean of 0, i.e. value from -1 to +1 by default:

In [37]:
# This function gives a single value at a time if we don't pass value shape parameter
np.random.randn()

0.6283247430188281

In [38]:
# **We can also produce 1-D numpy array of any shape by giving shape value parameter**
np.random.randn(3)

array([-0.04702554, -0.93795284,  0.26862279])

In [39]:
# We can also generate randomly 2D array by giving values of rows and columns
np.random.randn(5,3)

array([[-1.78942449,  1.23378729,  0.02428895],
       [-0.86995709, -0.35988004, -0.23218747],
       [-1.74334014, -0.12998265, -0.59951112],
       [-0.47224314,  1.03776274,  1.43753566],
       [ 0.01490817, -1.56532222,  0.65742642]])

In [40]:
# We can also generate randomly 3D array
array = np.random.randn(3,4,2)
array

array([[[ 0.70015016, -0.59662248],
        [-1.81687884, -0.82907438],
        [ 1.50912275,  0.91352194],
        [-0.52336749,  0.2105112 ]],

       [[-1.03288454, -0.86890325],
        [-0.01191241,  0.3242754 ],
        [ 0.97672409, -0.86775067],
        [-0.31891871,  0.00956254]],

       [[ 1.21307951, -0.62120759],
        [ 1.70837809,  1.31233036],
        [ 2.25821376,  1.51816714],
        [ 0.39982817, -1.74158959]]])

In [41]:
array.mean(), array.std()

(0.1593647983177192, 1.0894715707173563)

**As we can see distribution is still 1, the range of the given values does not change. The distribution value can be changed with an integer value by performing some arithmetic operations like `+`,`-`,`*`,`/`.**

In [42]:
result=np.random.randn(3,4)
result

array([[ 0.61399228, -0.29530387,  0.28278237,  1.05943832],
       [ 0.90524306, -0.09221336, -0.77167632, -0.86546231],
       [ 0.29005991, -0.88458505,  0.85739411,  2.40217724]])

In [43]:
result*3

array([[ 1.84197684, -0.8859116 ,  0.8483471 ,  3.17831495],
       [ 2.71572919, -0.27664008, -2.31502896, -2.59638693],
       [ 0.87017973, -2.65375514,  2.57218234,  7.20653171]])

In [44]:
result+3

array([[3.61399228, 2.70469613, 3.28278237, 4.05943832],
       [3.90524306, 2.90778664, 2.22832368, 2.13453769],
       [3.29005991, 2.11541495, 3.85739411, 5.40217724]])

The distribution is now equal to 4, so the given floats vary between minus and plus 4. Other mathematical operations such as multiplication, division, subtraction are possible in order to modify the distribution, depending on the needs.

#### np.random.randint()
It is one of the function for doing random sampling in numpy. It is used to generate whole random numbers, ranging between low(inclusive) and high(exclusive) value. Specifying a parameter like `(1, 100)` will create random values from 1 to 99.
#### Syntax : numpy.random.randint(low, high=None, size=None, dtype=’l’)

### Parameters :
- low : [int] Lowest (signed) integer to be drawn from the distribution.But, it works as a highest integer in the sample if high=None.
- high : [int, optional] Largest (signed) integer to be drawn from the distribution.
- size : [int or tuple of ints, optional] Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
- dtype : [optional] Desired output data-type.

In [47]:
import numpy as np
np.random.randint(low=10)

6

In [48]:
# another parameter that we can add into randint is `high`
np.random.randint(low=10, high=20)

18

In [49]:
# we can also a parameter `size` that defines the total number of elements in the array
np.random.randint(low=1, high=101, size=20)

array([64,  7, 56, 90, 69, 19, 30, 85, 97, 12,  9, 20,  8, 62, 12, 66, 48,
       59, 41, 26])

In [ ]:
# change the datatype of the numpy array using dtype parameter, by default , data-type is integer
np.random.randint(low=1, high=101, size=20, dtype=np.uint8)

In [50]:
# create a 2- multi-dimensional array using tuple in size parameter
np.random.randint(low=1, high=100, size=(5,3))

array([[79, 35, 71],
       [41, 96, 42],
       [92, 37, 73],
       [63,  2, 30],
       [50,  5,  1]])

In [51]:
# create a 3- multi-dimensional array using tuple in size parameter
arr1 = np.random.randint(low=1, high=100, size=(3,5,3))
arr1

array([[[64, 82, 58],
        [90, 48,  3],
        [29, 95,  5],
        [62, 66,  7],
        [34, 91, 24]],

       [[83, 73,  8],
        [ 3, 93, 71],
        [24, 48, 35],
        [54, 62,  7],
        [39, 74, 85]],

       [[26, 93,  4],
        [43, 38, 21],
        [95,  9, 27],
        [61, 19, 72],
        [91, 29,  9]]])

In [52]:
arr1.shape

(3, 5, 3)

In [ ]:
# what is numpy.
# np.array()
# np.arange(start, stop, step, dtype)
# np.zeros(shape) -> shape 1d, 2d, 3d, nd
# np.ones(shape) -> shape 1d,2d,3d, nd
# np.linspace(start, stop, num, dtype)
# np.eye(N=rows(int), M=columns(int), k=0(int), dtype=)
# np.random.rand(shape/size)
# np.random.randn(size/shape)
# np.random.randint(low,high,size, dtype)
# np.shape()
# np.dtype

# 5. Array Attributes and Methods

Now we will continue with more attributes and methods that can be used on arrays.

- np.reshape() – changes the shape of an array into the desired shape
- np.shape() – returns a tuple of the shape of the given array as parameter
- np.dtype() – returns the data type of the values in the array

These methods will improve your `trial-and-error(a finding out of the best way to reach a desired result or a correct solution by trying out one or more ways or means and by noting and eliminating errors or causes of failure)`, meaning, once you find yourself in a situation where you encounter an error, applying methods like this may help you locate the error faster, thus it will save you a lot of time in the future. Let’s dive straight in.

In [ ]:
import numpy as np

In [ ]:
# print(dir(np))

### np.reshape()
This method allows you to transform one dimensional array to more dimensional, or the other way around. Reshape will not affect your data values.

In [53]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
# shape() gives the number of rows and columns of numpy array as well as dataframe
print("Shape of numpy array is : ",a.shape)
# this means that `a` numpy object has 25 rows and 0 column

# ndim() gives the dimension of the numpy array, 1 means 1-d, 2-d, 3-d
print("Dimension of numpy array is : ",a.ndim)

Shape of numpy array is :  (25,)
Dimension of numpy array is :  1


In [55]:
b = a.reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
# Now, this numpy object has 5 columns and 5 rows , but the data of numy remains same
print("Shape of numpy array is : ",b.shape)

print("Dimension of numpy array is : ",b.ndim)

Shape of numpy array is :  (5, 5)
Dimension of numpy array is :  2


**Key thing to notice is that the array still has all 25 elements. Reshaping it into a 4 by 5 matrix(4 rows, 5 columns), would’ve produced an error since the reshape size is not the same size as the array’s. It would’ve been possible if the array had only 20 elements. To reverse the process and return the array into it’s original shape.**

In [57]:
a.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [58]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
# Reverse the `b` object into original numpy object
b.reshape(25,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### np.dtype()

This function allows you to check the data type of the array’s values.

There can be more the one data type present in an array, in the upcoming lectures we will in shaa allah discuss all `dtypes` in numpy array.

In [ ]:
a

In [ ]:
a.dtype

In [ ]:
c = np.linspace(start=1,stop=10)
c

In [ ]:
c.dtype

In [ ]:
str_array = np.array(["ehtisham", "ali", "ayesha", 23, 20, 17, 88.88, 90.45])

In [ ]:
str_array.dtype

# 6. Numpy Indexing and Selection
Here, we will discuss how to select element or groups of elements from an array and change them. There are two methods are used to perform these operations

- Indexing – pick one or more elements from an array
- Broadcasting – changing values within an index range

In [63]:
array = np.random.randint(low=10, high=20, size=6)
array

array([10, 16, 11, 16, 16, 11])

In [64]:
# Select first element of the array , as we know that indexing start from zero 
array[0]

10

In [65]:
# select last element of the array, as we know that index of last element is denoted by -1
array[-1] , array[len(array)-1]

(11, 11)

In [66]:
# we can also perform slicing on numpy array
print("Slicing from 2-4 index : ", array[2:5])


# we can also perform negative indexing on numpy object
print("Slicing from 2-4 index : ", array[-5:-2])

Slicing from 2-4 index :  [11 16 16]
Slicing from 2-4 index :  [16 11 16]


## indexing from 2-dimensional numpy array is different


In [60]:
data = np.linspace(start=10, stop=100,num=63, dtype=int)
data

array([ 10,  11,  12,  14,  15,  17,  18,  20,  21,  23,  24,  25,  27,
        28,  30,  31,  33,  34,  36,  37,  39,  40,  41,  43,  44,  46,
        47,  49,  50,  52,  53,  55,  56,  57,  59,  60,  62,  63,  65,
        66,  68,  69,  70,  72,  73,  75,  76,  78,  79,  81,  82,  84,
        85,  86,  88,  89,  91,  92,  94,  95,  97,  98, 100])

In [61]:
# give shape of the numpy object
data.shape

(63,)

In [62]:
dataReshaped = data.reshape(9,7)
dataReshaped

array([[ 10,  11,  12,  14,  15,  17,  18],
       [ 20,  21,  23,  24,  25,  27,  28],
       [ 30,  31,  33,  34,  36,  37,  39],
       [ 40,  41,  43,  44,  46,  47,  49],
       [ 50,  52,  53,  55,  56,  57,  59],
       [ 60,  62,  63,  65,  66,  68,  69],
       [ 70,  72,  73,  75,  76,  78,  79],
       [ 81,  82,  84,  85,  86,  88,  89],
       [ 91,  92,  94,  95,  97,  98, 100]])

In [67]:
# give shape of the numpy object
dataReshaped.shape

(9, 7)

In [68]:
# select element at first index
dataReshaped[1]

array([20, 21, 23, 24, 25, 27, 28])

In [69]:
# select last element of the 4th row
dataReshaped[1][-1]

28

In [70]:
dataReshaped[4][3]

55

### TASK :
Select first element of the 2nd last row

In [ ]:
dataReshaped

In [ ]:
dataReshaped[-2][0]

## indexing from 3-dimensional numpy array is different


In [71]:
data3d = np.random.randint(low=10, high=100, size=(4,3,3))
data3d

array([[[38, 70, 16],
        [58, 89, 96],
        [40, 70, 84]],

       [[84, 78, 63],
        [91, 32, 56],
        [94, 15, 70]],

       [[48, 39, 95],
        [70, 84, 44],
        [40, 36, 33]],

       [[23, 67, 25],
        [81, 56, 97],
        [22, 92, 29]]])

In [72]:
data3d.shape

(4, 3, 3)

In [73]:
# select matrix/array at first index
data3d[1]

array([[84, 78, 63],
       [91, 32, 56],
       [94, 15, 70]])

In [74]:
# select 2nd array from array at first index
data3d[1][1]

array([91, 32, 56])

In [75]:
# select 3rd element of 2nd array from array at first index 
data3d[1][1][2]

56

### Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast. Below is an example of setting a value within index range (Broadcasting).

In [76]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [77]:
d = a

In [78]:
print(d[3])
d[3] = 88
d

3


array([ 0,  1,  2, 88,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
a
# As you can see, change occurs in both arrays

array([ 0,  1,  2, 88,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [80]:
# setting value within index range
d[:5] = -3
print("Array d: ", d)
print("Array a : ", a)

Array d:  [-3 -3 -3 -3 -3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Array a :  [-3 -3 -3 -3 -3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [81]:
# List does support broadcasting
list1 = list(range(1,10))
list1[:5] = -5

TypeError: can only assign an iterable

In [82]:
# let's create a new numpy array
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
# change the first six values of our array, but firstly we slice it
slice_of_arr = arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [84]:
# after getting slice , we will change all the values to 5
slice_of_arr[:] = 5
slice_of_arr

array([5, 5, 5, 5, 5, 5])

In [85]:
# as values are also changed into original array, to avoid this we can use concept of copy function
arr

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [86]:
slice_of_arr1 = arr.copy()
slice_of_arr1

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [87]:
slice_of_arr1[:6] = 10
slice_of_arr1

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [88]:
# now the change in original array is not occured
arr

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

# 7. Indexing 2D Array/Matrix

The main idea behind this topic is to help you get comfortable with indexing in more than 1 dimensions. Below is a list of what we will discuss.

- Indexing a 2D array – Indexing matrices differs from vectors
- Fancy indexing – Selecting entire rows or columns out of order
- Selection – Selection based off of comparison operators

### Indexing a 2D array

The general format is `arr_2d[row][col]` or `arr_2d[row,col]`. I will recommend to use comma notation format.

In [89]:
# I have created 2-d array
arr_2D = np.array([[34,5,55],
                 [3,44,6],
                 [23,5,66]])
arr_2D

array([[34,  5, 55],
       [ 3, 44,  6],
       [23,  5, 66]])

In [90]:
print("Shape of numpy array : ",arr_2D.shape)
print("Dimension of numpy array : ",arr_2D.ndim)

Shape of numpy array :  (3, 3)
Dimension of numpy array :  2


In [91]:
# indexing of rows is fairly simple
arr_2D[0]

array([34,  5, 55])

In [92]:
# To get first value of arr_2d[0], we can do this
arr_2D[0][0]

34

In [93]:
arr_2D[0,0]

34

In [94]:
# select the 2nd column with all the its values
arr_2D[:,1]

array([ 5, 44,  5])

In [95]:
# It is possible to exclude the last column
arr_2D[:,:-1]

array([[34,  5],
       [ 3, 44],
       [23,  5]])

In [96]:
arr_2D

array([[34,  5, 55],
       [ 3, 44,  6],
       [23,  5, 66]])

In [97]:
# another example
arr_2D[:2,1:]

array([[ 5, 55],
       [44,  6]])

### Fancy Indexing
Fancy indexing allows you to select entire rows or columns out of order. To show this, let’s quickly build out a numpy array of zeros

In [98]:
arr_zeros = np.zeros((4,5), dtype=int)
arr_zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [99]:
arr_zeros.shape

(4, 5)

In [100]:
# 4 rows and 5 columns 
arrRows =arr_zeros.shape[0]
arrRows

4

In [101]:
for i in range(arrRows):
    arr_zeros[i] = i
arr_zeros

# we changed the values of each rows corresponding to its index value

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [108]:
arr_zeros[[1,3]]

array([[1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3]])

In [103]:
arr_zeros[[1,2]] # [2:5, :] or [[2,3,4], :]

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [109]:
arr_zeros[1:3]

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

### Selection
Selection defines how to use brackets for selection based off of comparison operators. As a result, it returns us `1-d array` of selected elements.

In [110]:
arr_Selection = np.arange(1,11)
arr_Selection

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
# select all the elements of the array greater than 4
arr_Selection > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [112]:
# To get the actual values, we need to put this into following manner
arr_Selection[arr_Selection<4]

array([1, 2, 3])

**We can also from selection on 2-D array.**

In [113]:
arr_2D

array([[34,  5, 55],
       [ 3, 44,  6],
       [23,  5, 66]])

In [114]:
# elements whose values are greater than 7
# arr_2D[arr_2D>10]
arr_2D[arr_2D>10]

array([34, 55, 44, 23, 66])

# 8. Numpy Operations
We can perform different types of operations on NumPy arrays. What this means is we can sum, subtract, multiply or divide the values inside our array, even do things like taking the square root. Below is a list of what we will discuss in this lecture.
- Arithmetic Operations – sum, subtract, multiply, divide on arrays
- Universal Array Functions – Mathematical operations provided by NumPy

### Arithmetic
While performing arithmetic operations between two arrays it is important that they have the same dimensions. 

In [115]:
# create 1-d array
ArrOperations = np.arange(11)
ArrOperations

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
# addition/sum of two arrays
ArrOperations + ArrOperations

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [117]:
# subtraction of two arrays
ArrOperations-ArrOperations

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [118]:
# multilication of two arrays
ArrOperations*ArrOperations

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [119]:
# division of two arrays
ArrOperations/ArrOperations

/var/folders/qb/lf_2q09x7wj115gvfnkv6tkm0000gn/T/ipykernel_30424/2324457737.py:2: RuntimeWarning: invalid value encountered in divide
  ArrOperations/ArrOperations


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

**Note: Warning indicates that divison with zero was encountered and all the valued divided with zero will be None.**

In [120]:
# Cube of array
ArrOperations**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [121]:
# multiply array with 3
ArrOperations*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [122]:
1/ArrOperations

/var/folders/qb/lf_2q09x7wj115gvfnkv6tkm0000gn/T/ipykernel_30424/3505209312.py:1: RuntimeWarning: divide by zero encountered in divide
  1/ArrOperations


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [123]:
# arithmetic operations on 2-D array
arr_2D

array([[34,  5, 55],
       [ 3, 44,  6],
       [23,  5, 66]])

In [124]:
# addition 
arr_2D+arr_2D

array([[ 68,  10, 110],
       [  6,  88,  12],
       [ 46,  10, 132]])

In [125]:
# subtraction
arr_2D-arr_2D

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [126]:
# multiplication
arr_2D*arr_2D

array([[1156,   25, 3025],
       [   9, 1936,   36],
       [ 529,   25, 4356]])

In [127]:
# division
arr_2D/arr_2D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [128]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
arr2 = np.arange(8)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [130]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (10,) (8,) 

In [132]:
#arr1.sum(arr2)
np.sum(arr1, arr2)

TypeError: only integer scalar arrays can be converted to a scalar index

### Universal Array Functions

Numpy comes with many universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array. Let’s show some common ones.

In [133]:
# square root of 1-D array
np.sqrt(ArrOperations)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [134]:
# square root of 2-D array
np.sqrt(arr_2D)

array([[5.83095189, 2.23606798, 7.41619849],
       [1.73205081, 6.63324958, 2.44948974],
       [4.79583152, 2.23606798, 8.1240384 ]])

In [135]:
# Exponential of 1-D array
np.exp(ArrOperations)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
# Exponential of 2-D array
np.exp(arr_2D)

In [136]:
# max and min value of array
print("Max value of 1-D array is : ", np.max(ArrOperations))
print("Max value of 2-D array is:", np.max(arr_2D))

Max value of 1-D array is :  10
Max value of 2-D array is: 66


In [137]:
# max and min value of array
print("Min value of 1-D array is : ", np.min(ArrOperations))
print("Min value of 2-D array is : ", np.min(arr_2D))

Min value of 1-D array is :  0
Min value of 2-D array is :  3


In [138]:
# log of array
print("Log of 1-D array is : ", np.log(ArrOperations))
print("\n\n")
print("Log of 2-D array is : ", np.log(arr_2D))

Log of 1-D array is :  [      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]



Log of 2-D array is :  [[3.52636052 1.60943791 4.00733319]
 [1.09861229 3.78418963 1.79175947]
 [3.13549422 1.60943791 4.18965474]]


/var/folders/qb/lf_2q09x7wj115gvfnkv6tkm0000gn/T/ipykernel_30424/370656916.py:2: RuntimeWarning: divide by zero encountered in log
  print("Log of 1-D array is : ", np.log(ArrOperations))


**Note : When dealing with messy data you will often need to stick multiple arrays together.**

### Test Yourself
- Addition, Subtraction etc on different size of arrays
    - Broadcasting 
    - Padding the smaller array
    - Trimming the larger array

# 9. Append, Concatenate and Stack

- np.append() – append one array to another
- np.concatenate() – Concatenate two arrays
- np.stack() – Stack one array to another horizontally or vertically

### numpy.append()

- The numpy.append() function is used to add or append new values to an existing numpy array. 
- This function adds the new values at the end of the array.
- The numpy append() function is used to merge two arrays. 
- It returns a new array, and the original array remains unchanged.

### Syntax: 
**numpy.append(arr, values, axis=None)**
- arr: array_like (This is a ndarray. The new values are appended to a copy of this array. This parameter is required and plays an important role in numpy.append() function.)
- values: array_like (This parameter defines the values which are appended to a copy of a ndarray. One thing is to be noticed here that these values must be of the correct shape as the original ndarray, excluding the axis. If the axis is not defined, then the values can be in any shape and will flatten before use.)
- axis: int(optional) (This parameter defines the axis along which values are appended. When the axis is not given to them, both ndarray and values are flattened before use.)

In [ ]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b = np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c = np.append(arr = a,values = b)  

In [ ]:
print("Array a is : ", a, sep="\n")
print("\n\n")
print("Array b is : ", b, sep="\n")
print("\n\n")
print("New array c is : ", c, sep="\n")

In the output, values of both arrays, i.e., `a` and `b`, have been shown in the flattened form, and the original array remained same because `axis=None`.

In [ ]:
# appending according rows 
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b = np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c = np.append(arr= a,values = b, axis=0)  
print("Array a is : ", a, sep="\n")
print("\n\n")
print("Array b is : ", b, sep="\n")
print("\n\n")
print("New array c is : ", c, sep="\n")

In [ ]:
# appending according columns
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b = np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c = np.append(arr= a,values = b, axis=1)  
print("Array a is : ", a, sep="\n")
print("\n\n")
print("Array b is : ", b, sep="\n")
print("\n\n")
print("New array c is : ", c, sep="\n")

### Numpy.concatenate()
**This function is basically used for joining two or more arrays of the same shape along a specified axis.**     
There are the following things which are essential to keep in mind:
- Concatenate works similarly to append, but instead of ‘arr’ and ‘values’ as parameters it takes a tuple of two arrays. 
- NumPy's concatenate() is not like a traditional database join. It is like stacking NumPy arrays.
- This function can operate both vertically and horizontally. This means we can concatenate arrays together horizontally or vertically.
<img src="images/numpy-concatenate.png">

**Syntax: numpy.concatenate((a1, a2, ...), axis)**

In [ ]:
# concatenate numpy arrays without passing parameter axis
x = np.array([[1,2],[3,4]])  
y = np.array([[12,30]])  
x, x.shape

In [ ]:
y, y.shape

In [ ]:
z = np.concatenate((x,y))  
z  

In [ ]:
# concatenate numpy arrays passing parameter axis=0
x = np.array([[1,2],[3,4]])  
y = np.array([[12,30]])  
z = np.concatenate((x,y), axis=0)  
z  

In [ ]:
# concatenate numpy arrays passing parameter axis=1
x = np.array([[1,2],[3,4]])  
y = np.array([[12,30]])  
z = np.concatenate((x,y), axis=1)  
z

In [ ]:
# concatenate numpy arrays passing parameter axis=1
x = np.array([[1,2],[3,4]])  
y = np.array([[12,30]])  
z = np.concatenate((x,y.T), axis=1)  
z  

In [ ]:
# concatenate numpy arrays passing parameter axis=None
x = np.array([[1,2],[3,4]])  
y = np.array([[12,30]])  
z = np.concatenate((x,y.T), axis=None)  
z  

### Stack
<img src="images/StackDS.jpg" width="500px" height="500px">

There are two ways of stacking arrays together, horizontally and vertically.
<img src="images/stack.png" height="600px" width="600px">

In [ ]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print("Numpy a is : ", a, sep="\n")

In [ ]:

b = np.array([[1,2,3,4],
             [5,6,7,8]])
print("Numpy b is : ", b, sep="\n")

c = np.array([[1,2],
             [3,4],
             [5,6]])
print("Numpy c is : ", c, sep="\n")

In [ ]:
# example of vertical stack
verticalStack = np.vstack((a,b))
verticalStack

In [ ]:
# example of horizontal stack
horizontalStack = np.hstack((a,c))
horizontalStack

In [ ]:
a

# Check Concepts:
- What is NumPy Library?
- Why we use Numpy Library or where NumPy is used?
- How to create 1D, 2D and 3D Array ?
- How to get shape for 1D, 2D and 3D Array ?
- How to identified datatyp for numpy array?
- Print numpy array of zeros with 2 rows and 3 columns ?
- What is difference between `np.eye()` and `np.diag()` and also give example to elaborate the difference.?
- Print a range between 1 To 15 and show only 4 integers random numbers.
- Print a range of random numbers having 2 row and 3 cols integers random numbers.
- What Is The Preferred Way To Check For An Empty (zero Element) Array?
- How many dimensions can a NumPy array have?
 > In NumPy, an array can have N-dimensions, and is called a ndarray.
        > Ndarray is a multidimensional container which contains elements of the same type and size.
        > The number of dimensions in a ndarray is also known as ‘rank’.
        > A tuple of integers called ‘shape’ defines the size of the array in each dimension.
        > The data type of elements in ndarray is defined by a ‘dtype’ object.
- Print the last element from the 2nd dimension array.
- Explain the operations that can be performed in NumPy.
- What is a vector?
- How do you represent vectors using a Python list? Give an example.
- What is a dot product of two vectors?
- Write a function to compute the dot product of two vectors.
- What does it mean to import a module with an alias? Give an example.
- What is the commonly used alias for numpy?
- What is the type of Numpy arrays?
- How do you access the elements of a Numpy array?
- What happens if you try to compute the dot product of two vectors which have different sizes?

In [ ]:
# a = np.arange(10,17)
# b = np.arange(1,8)
# a,b
# np.dot(a,b)

# Practice Exercises

#### Exercise 1: 
Create a 4X2 integer array and Prints its attributes.    
**Note: The element must be a type of unsigned int16. And print the following Attributes: –**

- The shape of an array.
- Array dimensions.
- The Length of each element of the array in bytes.


In [ ]:
# Here write your answer
array = np.random.randint(10,30,size=(4,2), dtype=np.uint16)
array

In [ ]:
print("Array : ", array, sep="\n")
print("Shape : ", array.shape)
print("Dimensions : ", array.ndim)
print("Size of array : ", array.size)
print("Length of each element in bytes is : ", array.itemsize)
print("Length of array in bytes is : ", array.nbytes)

#### Exercise 2: 
Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10.    
**Hint: Use np.arange() and reshape() function.**

In [ ]:
# np.arange(100,200,10).reshape(5,2)

In [ ]:
np.linspace(100,200,num=10, dtype=int).reshape(5,2)

In [ ]:
# Here write your answer
# np.arange(100,200,10).reshape(5,2)
# np.linspace(100,200,num=10, dtype=int).reshape(5,2)

#### Exercise 3: 
Following is the provided numPy array. Return array of items by taking the third column from all rows.    
**sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])**

In [ ]:
# Here write your answer
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray

In [ ]:
# sampleArray[:,-1]

In [ ]:
sampleArray[:,-1]

## BOUNS TASK

In [ ]:
import numpy
import matplotlib.pyplot as plt
# sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray = np.random.randint(10,26,(825,825))
sampleArray
plt.matshow(sampleArray)
plt.show()

In [ ]:
import numpy
import matplotlib.pyplot as plt

print("Printing Original array")
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)
plt.matshow(sampleArray) # ploting original array


print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray , 1, axis = 1) 
print(sampleArray)

arr = numpy.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)
plt.matshow(sampleArray) # ploting after updation


# NumPy - Assignment no 01
- Here is address of [NumPy -Assignment no 01](https://www.kaggle.com/code/ehtishamsadiq/numpy-assignment-no-01)

In [1]:
from IPython.core.display import HTML

style = """
    <style>
        body {
            background-color: #f2fff2;
        }
        h1 {
            text-align: center;
            font-weight: bold;
            font-size: 36px;
            color: #4295F4;
            text-decoration: underline;
            padding-top: 15px;
        }
        
        h2 {
            text-align: left;
            font-weight: bold;
            font-size: 30px;
            color: #4A000A;
            text-decoration: underline;
            padding-top: 10px;
        }
        
        h3 {
            text-align: left;
            font-weight: bold;
            font-size: 30px;
            color: #f0081e;
            text-decoration: underline;
            padding-top: 5px;
        }

        
        p {
            text-align: center;
            font-size: 12 px;
            color: #0B9923;
        }
    </style>
"""

html_content = """
<h1>Hello</h1>
<p>Hello World</p>
<h2> Hello</h2>
<h3> World </h3>
"""

HTML(style + html_content)